name: Run Memote test

on:
  pull_request:
    branches: [main]

jobs: 
  run-memote:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kennetlindquist/e-coli-standard-gem-env:latest
      options: --user root --workdir /project
      volumes:
        - ${{ github.workspace }}:/project:rw

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Run Memote script
        run: python code/memote_test.py      

      - name: Mark directory as safe
        run: git config --global --add safe.directory /__w/Ecoli-GEM/Ecoli-GEM

      - name: Commit and push report to repository
        uses: EndBug/add-and-commit@v9
        with: 
          author_name: 'github-actions[bot]'
          message: 'ci(memote): add Memote HTML report [skip ci]'
          add: 'memote_report.html'
